[package]
name = "b58"
version = "0.1.0"
edition = "2021"
authors = ["Joshua J. Bouw <dev@joshuajbouw.com>"]
license = "CC0-1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base58 = "0.2"
hex = "0.4"
